version: '1.0'
services:
  bridge_app:
    image: "geos74/bridge:0.0.2"
    ports:
      - "3100:3500"
    environment:
      - SERVER_PORT=3500
      - DB_USER=bridge
      - DB_HOST=db_bridge
      - DB_NAME=bridge
      - DB_PASS=admin
      - NODE_ENV=dev
    volumes:
      - init-db-bridge:/bridge/libs
    deploy:
      resources:
        limits:
          memory: 50M
  db_bridge:
    image: "postgres"
    volumes:
      - init-db-bridge:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=bridge
      - POSTGRES_DB=bridge
    deploy:
      resources:
        limits:
          memory: 50M
  mauth_app:
    image: "geos74/mauth:1.0.0"
    ports:
      - "3001:3001"
    environment:
      - SERVER_PORT=3001
      - NODE_ENV=dev
      - SERVER_DOMAIN=localhost:8080
      - DB_USER=mauth
      - DB_HOST=db_mauth
      - DB_NAME=mauth
      - DB_PASS=admin
      - MAIL_USER=carson.kunde24@ethereal.email
      - MAIL_PASS=2uzPaY8qYFN7xbDyHm
      - MAIL_HOST=smtp.ethereal.email
      - MAIL_PORT=587
      - MAIL_SECURE=false
      - IGNORE_TLS=false
      - JWT_TTL=1800
      - JWT_SECRET_KEY="any secret"
      - VERIFICATION_TTL="10 minute"
      - SESSION_TTL="30 day"
      - TPL_CONFIRM_PATH=/auth/confirm
      # - TPL_RECOVERY_PATH=/api/mauth/forgot
    volumes:
      - init-db-mauth:/mauth/libs
    deploy:
      resources:
        limits:
          memory: 50M
  db_mauth:
    image: "postgres"
    volumes:
      - init-db-mauth:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=mauth
      - POSTGRES_DB=mauth
    deploy:
      resources:
        limits:
          memory: 50M
  react:
    build: .
    ports:
      - "8080:80"
    environment:
      - HOST_BRIDGE=bridge_app
      - PORT_BRIDGE=3500
      - HOST_MAUTH=mauth_app
      - PORT_MAUTH=3001
volumes:
  init-db-bridge:
  init-db-mauth:
